# Generated by Django 2.2.4 on 2019-08-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome',
            new_name='categoria',
        ),
    ]
